app.url=http://localhost:8080/scheduleappointment

mail.username=183anhka@gmail.com
mail.password=kgge xtym cmfm hrxb

db.url=jdbc:sqlserver://localhost:1433;databaseName=scheduleappointment;encrypt=true;trustServerCertificate=true
db.username=sa
db.password=123

somee.url=jdbc:sqlserver://scheduleappointment.mssql.somee.com;databaseName=scheduleappointment;encrypt=true;trustServerCertificate=true
somee.username=KaKaKaaaaa_SQLLogin_1
somee.password=czbmw6le1d